name: Docker CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push the Docker image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker build -t shyamportfolio/portfolio:latest .
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        docker push shyamportfolio/portfolio:latest

  deploy: 
    needs: build 
    runs-on: [ip-172-31-21-217]
    steps:
      - name: pull image from docker Hub
        run: docker pull shyamportfolio/portfolio:latest

      - name: delete old container
        run: docker rm -f portfolio-container
        
      - name: run docker container
        run: docker run -d -p 5000:5000 --name portfolio-container portfolio shyamportfolio/portfolio
