name: Docker CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Node setup
      uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASS }}

    - name: Build the Docker image
      run: docker build -t shyamportfolio/portfolio:latest .

    - name: Publish docker image
      run: docker push shyamportfolio/portfolio:latest

  deploy: 
    needs: build 
    runs-on: [ip-172-31-21-217]
    steps:
      - name: Pull image from Docker Hub
        run: docker pull shyamportfolio/portfolio:latest

      - name: Delete old container
        run: docker rm -f portfolio-container
        
      - name: Run Docker container
        run: docker run -d -p 5000:5000 --name portfolio-container shyamportfolio/portfolio
