name: Docker CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASS }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: bishtshyam095/portfolio:latest

  deploy: 
    needs: build 
    runs-on: [aws-ec2]
    steps:
      - name: Install Docker
        run: |
         sudo yum update -y
         sudo yum install docker -y
         sudo systemctl start docker
         sudo systemctl enable docker 
         sudo usermod -aG docker ec2-user
         sudo newgrp docker
         sudo systemctl status docker

      - name: install nginx
        run: |
          sudo yum install nginx -y
          sudo systemctl start nginx
          sudo systemctl enable nginx
          sudo systemctl status nginx

      - name: Pull image from Docker Hub
        run: docker pull bishtshyam095/portfolio:latest

      - name: Delete old container
        run: docker rm -f portfolio-container
        
      - name: Run Docker container
        run: docker run -d -p 5000:80 --name portfolio-container bishtshyam095/portfolio
      
      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          # Slack channel id, channel name, or user id to post message.
          # See also: https://api.slack.com/methods/chat.postMessage#channels
          # You can pass in multiple channels to post to by providing a comma-delimited list of channel IDs.
          channel-id: 'T06777UNKPW/D0674Q55JHY'
          # For posting a simple plain text message
          slack-message: "GitHub build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
