name: Slack Integration

on:
  push:
    branches:
      - features
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Add your build, test, deploy steps here

      - name: Notify Slack
        if: always() # This ensures the notification is sent even if previous steps fail
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Hello, World!"}' https://hooks.slack.com/services/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
